// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace NeuralNetworks
{
    public partial class MLP
    {
        /// <summary>
        /// model input class for MLP.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"theta1")]
            public float Theta1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"theta2")]
            public float Theta2 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"theta3")]
            public float Theta3 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"theta4")]
            public float Theta4 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"theta5")]
            public float Theta5 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"theta6")]
            public float Theta6 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"thetad1")]
            public float Thetad1 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"thetad2")]
            public float Thetad2 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"thetad3")]
            public float Thetad3 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"thetad4")]
            public float Thetad4 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"thetad5")]
            public float Thetad5 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"thetad6")]
            public float Thetad6 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"tau1")]
            public float Tau1 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"tau2")]
            public float Tau2 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"tau3")]
            public float Tau3 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"tau4")]
            public float Tau4 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"tau5")]
            public float Tau5 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"dm1")]
            public float Dm1 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"dm2")]
            public float Dm2 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"dm3")]
            public float Dm3 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"dm4")]
            public float Dm4 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"dm5")]
            public float Dm5 { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"da1")]
            public float Da1 { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"da2")]
            public float Da2 { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"da3")]
            public float Da3 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"da4")]
            public float Da4 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"da5")]
            public float Da5 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"db1")]
            public float Db1 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"db2")]
            public float Db2 { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"db3")]
            public float Db3 { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"db4")]
            public float Db4 { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"db5")]
            public float Db5 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"ANGLE-ACC-ARM")]
            public float ANGLE_ACC_ARM { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLP.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"theta1")]
            public float Theta1 { get; set; }

            [ColumnName(@"theta2")]
            public float Theta2 { get; set; }

            [ColumnName(@"theta3")]
            public float Theta3 { get; set; }

            [ColumnName(@"theta4")]
            public float Theta4 { get; set; }

            [ColumnName(@"theta5")]
            public float Theta5 { get; set; }

            [ColumnName(@"theta6")]
            public float Theta6 { get; set; }

            [ColumnName(@"thetad1")]
            public float Thetad1 { get; set; }

            [ColumnName(@"thetad2")]
            public float Thetad2 { get; set; }

            [ColumnName(@"thetad3")]
            public float Thetad3 { get; set; }

            [ColumnName(@"thetad4")]
            public float Thetad4 { get; set; }

            [ColumnName(@"thetad5")]
            public float Thetad5 { get; set; }

            [ColumnName(@"thetad6")]
            public float Thetad6 { get; set; }

            [ColumnName(@"tau1")]
            public float Tau1 { get; set; }

            [ColumnName(@"tau2")]
            public float Tau2 { get; set; }

            [ColumnName(@"tau3")]
            public float Tau3 { get; set; }

            [ColumnName(@"tau4")]
            public float Tau4 { get; set; }

            [ColumnName(@"tau5")]
            public float Tau5 { get; set; }

            [ColumnName(@"dm1")]
            public float Dm1 { get; set; }

            [ColumnName(@"dm2")]
            public float Dm2 { get; set; }

            [ColumnName(@"dm3")]
            public float Dm3 { get; set; }

            [ColumnName(@"dm4")]
            public float Dm4 { get; set; }

            [ColumnName(@"dm5")]
            public float Dm5 { get; set; }

            [ColumnName(@"da1")]
            public float Da1 { get; set; }

            [ColumnName(@"da2")]
            public float Da2 { get; set; }

            [ColumnName(@"da3")]
            public float Da3 { get; set; }

            [ColumnName(@"da4")]
            public float Da4 { get; set; }

            [ColumnName(@"da5")]
            public float Da5 { get; set; }

            [ColumnName(@"db1")]
            public float Db1 { get; set; }

            [ColumnName(@"db2")]
            public float Db2 { get; set; }

            [ColumnName(@"db3")]
            public float Db3 { get; set; }

            [ColumnName(@"db4")]
            public float Db4 { get; set; }

            [ColumnName(@"db5")]
            public float Db5 { get; set; }

            [ColumnName(@"ANGLE-ACC-ARM")]
            public float ANGLE_ACC_ARM { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLP.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
